### ISSUE TITLE
Landungsbruecke Firmware for TMC4671_TMC6100-BOB

### ISSUE THREAD

**Issue by xiemark** [analogdevicesinc/TMC-EvalSystem#1]
I just found the hex file for TMC4671_TMC6100-BOB is not able to update.
https://www.trinamic.com/fileadmin/assets/Products/Eval_Software/Landungsbruecke_Firmware_for_TMC4671_TMC6100-BOB.zip

It said the hardware ID code does not match.

Do you provide hex file or source code for TMC4671_TMC6100-BOB?

Thanks!

**Comment by trinamic-ed** [comment]
Hello,

for the combination of the TMC4671_TMC6100-BOB, a small change must be made in this file [boards/TMC6100_eval.c](https://github.com/trinamic/TMC-EvalSystem/blob/master/boards/TMC6100_eval.c) in line 19 before compiling. The line must be uncommented for the bob, because the bob uses both ICs with the same SPI channel and the Landungsbrücke typically uses seperated channels for motion controller and driver.

Which hardware version are you using? With NXP or GD MCU?

Regards,
     Enrico

**Comment by xiemark** [comment]
Hi,
I use Landungsbrücke with MK20DX256 MCU. I think I can recompile the source codes.
Thank you!
